### ISSUE TITLE
DeprecationWarning: datetime.datetime.utcnow()

### ISSUE THREAD

**Issue by ways** [metno/bris-inference#55]
This warning is from python 3.12:

```
tests/test_outputs_netcdf.py::test_domain_name
  /home/larsfp/src/bris-inference/bris/outputs/netcdf.py:399: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    datestr = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S +00:00")
```

**Comment by ways** [comment]
```
>       datestr = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M:%S +00:00")
E       AttributeError: module 'datetime' has no attribute 'UTC'
```

Ouch. This doesn't work in python 3.10. Will find a different solution.
